theme: jekyll-agency

url    : "https://vika95viktoria.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/rijschool_website" # the subpath of your site, e.g. /blog


#
#plugins:
#  - jekyll-seo-tag
#  - jekyll-sitemap

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here


markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"