backend:
  name: git
  repo: vika95viktoria/rijschool_website  # Replace with your actual repo URL (e.g. user/repo)
  branch: master                                 # or "master," depending on your default branch

media_folder: "assets/img"  # Where images etc. are uploaded
public_folder: "/assets/img"

# Add collections to manage different content types
collections:

  - name: "pages"
    label: "Pages"
    files:
      - label: "Rates"
        name: "rates"
        file: "rates.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
