# admin/config.yml

backend:
  name: netlify
  # 'site_domain' points to your Netlify site domain (will configure later).
  # If you're testing locally or haven't deployed yet, you can leave this out
  # or temporarily use a placeholder. Once you know your Netlify domain,
  # add it here:
  site_domain: rijschool-xyz.netlify.app
  # If you use Netlify Identity, set:
  repo: vika95viktoria/rijschool_website # your GitHub repo
  branch: master # or 'master' or whichever branch you use

# Where to store media uploads (images, etc.)
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Collections define what content can be edited in the CMS.
collections:
  - name: "pages"
    label: "Pages"
    # We use 'files' here since you want to edit individual .md files in the root.
    files:
      - label: "Rates Page"
        name: "rates"
        file: "rates.md"  # Points to the root-level Markdown file in your repo
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "page"
          - label: "Custom Field"
            name: "custom_field"
            widget: "string"
          - label: "Background"
            name: "background"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
