# admin/config.yml

backend:
  name: git-gateway
  # 'site_domain' points to your Netlify site domain (will configure later).
  # If you're testing locally or haven't deployed yet, you can leave this out
  # or temporarily use a placeholder. Once you know your Netlify domain,
  # add it here:
  site_domain: rijschool-xyz.netlify.app
  # If you use Netlify Identity, set:
  repo: vika95viktoria/rijschool_website # your GitHub repo
  branch: master # or 'master' or whichever branch you use

# Where to store media uploads (images, etc.)
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Collections define what content can be edited in the CMS.
collections:
  - name: "pages"
    label: "Pages"
    # We use 'files' here since you want to edit individual .md files in the root.
    files:
      - label: "Rates Page"
        name: "rates"
        file: "rates.md"  # Points to the root-level Markdown file in your repo
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "page"
  - name: "sitetext"
    label: "Site Text"
    files:
      - label: "Site Text Data"
        name: "sitetext"
        file: "_data/sitetext.yml"

        # Fields define the structure of your YAML.
        fields:
          # 1) Rates
          - name: "rates"
            label: "Rates"
            widget: "object"
            fields:
              - name: "trial_lesson"
                label: "Trial Lesson"
                widget: "object"
                fields:
                  - { name: "duration", label: "Duration", widget: "string" }
                  - { name: "price", label: "Price", widget: "string" }

              - name: "one_lesson"
                label: "One Lesson"
                widget: "object"
                fields:
                  - { name: "duration", label: "Duration", widget: "string" }
                  - { name: "price", label: "Price", widget: "string" }
              - name: "five_lessons"
                label: "Five Lessons"
                widget: "object"
                fields:
                  - { name: "price", label: "Price", widget: "string" }
              - name: "ten_lessons"
                label: "Ten Lessons"
                widget: "object"
                fields:
                  - { name: "price", label: "Price", widget: "string" }
              - name: "twenty_lessons"
                label: "Twenty Lessons"
                widget: "object"
                fields:
                  - { name: "price", label: "Price", widget: "string" }
              - name: "thirty_lessons"
                label: "Thirty Lessons"
                widget: "object"
                fields:
                  - { name: "price", label: "Price", widget: "string" }
              - name: "practical_exam"
                label: "Practical Exam"
                widget: "object"
                fields:
                  - { name: "price", label: "Price", widget: "string" }







