name: Build and Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ "master" ]  # or your primary branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0  # or 3.0, 3.1, etc., whichever you use

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # If you want to force clean the gh-pages branch:
          # empty_commits_history: true
          # commit_message: "Deploy Jekyll site"